-- local augroup = vim.api.nvim_create_augroup("vimrc", { clear = true })
-- vim.api.nvim_create_autocmd({ "BufWritePost" }, {
--   group = augroup,
--   pattern = { "options.lua", "mappings.lua" },
--   command = "source $MYVIMRC",
-- })
