local o = vim.o
o.guifont = "Sarasa Fixed SC Nerd Font:h13"
o.autochdir = false
o.cursorline = true
o.ignorecase = true
o.number = true
o.relativenumber = true
o.cursorlineopt = "both"
o.shortmess = 'I'
o.tabstop = 4
o.shiftwidth = 4
